CXX = em++
CXXFLAGS = -g  --preload-file res --use-preload-plugins -Iinclude -std=c++1y -Iinclude -Inoudar-core/noudar-core/include -Istb

OBJS = src/CGame.o  SDLVersion/main.o SDLVersion/CSDLRenderer.o src/NativeBitmap.o src/LoadPNG.o noudar-core/noudar-core/src/CPlainFileLoader.o noudar-core/noudar-core/src/Common.o 


TARGET = game.html

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(CXXFLAGS)

all:   $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm game.data
	rm game.js	